"""
14b_build_generators_2024.py
Builds generators_2024.csv with p_nom calculated from real CAMMESA 2024 data.
Requires conflicts_psse_cammesa.csv to be completed (generated by script 14).

Inputs:
    data/network_500kv/generators_final.csv
    data/network_500kv/conflicts_psse_cammesa.csv
    Official data/valores_2024_clean.csv  (external — download from GitHub Releases, place in external_data_dir/)

Output:
    data/network_500kv/generators_2024.csv

p_nom logic:
    Direct match (bus_name_origen exists as a CAMMESA unit code):
        p_nom = 95th percentile of available_capacity_mw for that specific unit.

    Match by nemo4 (bus_name_origen not a CAMMESA unit, but nemo4 exists
    as a plant code in CAMMESA):
        p_nom = 95th percentile of available_capacity_mw for the entire plant,
        distributed proportionally to pt_mw from PSS/E among the plant's units.

    In both cases p95 is used to avoid point outliers.

    Binational plant SGDE (Salto Grande, Argentina/Uruguay):
    CAMMESA reports total plant output. Factor 0.5 is applied before
    computing p_nom to keep only the Argentine share.

    Carrier vs CAMMESA type validation:
    Units whose model carrier is incompatible with the type reported by
    CAMMESA for that plant or unit are automatically excluded. This prevents
    PSS/E-misclassified units from receiving generation profiles of a
    different technology.

Conflict resolution:
    Overrides from conflicts_psse_cammesa.csv are applied:
        exclude = yes             -> unit excluded from model
        corrected_unit_name       -> replaces bus_name_origen for CAMMESA matching
        reviewed = yes (no match) -> goes to nemo4 matching normally

    If there are pending conflicts (neither excluded nor reviewed nor matched),
    the script warns and exits without generating output.

Run from the repository root (pypsa-ar-base/):
    python scripts/network_500kv/14b_build_generators_2024.py
"""

import os
import sys
from pathlib import Path
import yaml
import pandas as pd
import numpy as np

# =============================================================================
# CONFIGURATION
# =============================================================================

_cfg = yaml.safe_load(open(Path(__file__).parents[2] / "config.yaml"))
REPO_DIR     = Path(_cfg["repo_dir"])
EXTERNAL_DIR = Path(_cfg["external_data_dir"])

GEN_FILE       = REPO_DIR / "data/network_500kv/generators_final.csv"
CONFLICTS_FILE = REPO_DIR / "data/network_500kv/conflicts_psse_cammesa.csv"
VALORES_FILE   = EXTERNAL_DIR / "valores_2024_clean.csv"
OUTPUT_DIR     = REPO_DIR / "data/network_500kv"
OUTPUT_FILE    = OUTPUT_DIR / "generators_2024.csv"

BINATIONAL_FACTOR = {'SGDE': 0.5}
P_NOM_PERCENTILE  = 95

# Valid CAMMESA carrier types per model carrier.
# Units whose CAMMESA type does not match any valid type for their carrier
# are automatically excluded.
CARRIER_VALID_TYPES = {
    'hydro'       : ['hydro', 'hydro_renewable'],
    'pumped_hydro': ['hydro'],
    'ocgt'        : ['ocgt', 'ccgt', 'steam'],
    'ccgt'        : ['ccgt', 'ocgt'],
    'steam'       : ['steam', 'ccgt', 'ocgt'],
    'nuclear'     : ['nuclear'],
    'wind'        : ['wind'],
    'solar'       : ['solar'],
    'diesel'      : ['diesel'],
    'biogas'      : ['biogas'],
    'biomass'     : ['biomass'],
}


# =============================================================================
# MAIN
# =============================================================================

def main():
    print("=" * 60)
    print("14b_build_generators_2024.py -- real 2024 generator table")
    print("=" * 60)

    for f in [GEN_FILE, CONFLICTS_FILE, VALORES_FILE]:
        if not os.path.isfile(f):
            print(f"[ERROR] File not found:\n  {f}")
            sys.exit(1)

    # =========================================================
    # LOAD GENERATORS AND CONFLICTS
    # =========================================================
    gen = pd.read_csv(GEN_FILE)
    gen['nemo4'] = gen['nemo'].fillna('').str[:4].str.strip()

    conflicts = pd.read_csv(CONFLICTS_FILE, encoding='latin-1')

    print(f"\nUnits in model : {len(gen)}")

    # Check for pending conflicts
    has_match   = conflicts['corrected_unit_name'].fillna('').str.strip() != ''
    is_excluded = conflicts['exclude'].fillna('').str.strip().str.lower() == 'yes'
    is_reviewed = conflicts['reviewed'].fillna('').str.strip().str.lower() == 'yes'
    pending     = conflicts[~has_match & ~is_excluded & ~is_reviewed]

    if len(pending) > 0:
        print(f"\n[ERROR] {len(pending)} pending conflicts in {CONFLICTS_FILE}")
        print(pending[['gen_key', 'bus_name_origen', 'nemo4']].to_string(index=False))
        print("\nComplete the CSV and re-run script 14.")
        sys.exit(1)

    # =========================================================
    # APPLY CONFLICT RESOLUTIONS
    # =========================================================
    exclude_keys = set(conflicts[is_excluded]['gen_key'].astype(str))
    gen = gen[~gen['gen_key'].astype(str).isin(exclude_keys)].copy()
    print(f"Units excluded by conflict   : {len(exclude_keys)}")

    match_map     = conflicts[has_match].set_index('gen_key')['corrected_unit_name'].to_dict()
    mask_override = gen['gen_key'].astype(str).isin(match_map)
    gen.loc[mask_override, 'bus_name_origen'] = (
        gen.loc[mask_override, 'gen_key'].astype(str).map(match_map)
    )
    print(f"Overrides applied            : {mask_override.sum()}")

    gen['nemo4'] = gen['nemo'].fillna('').str[:4].str.strip()

    # =========================================================
    # COMPUTE p95 PER UNIT AND PER PLANT FROM CAMMESA
    # =========================================================
    print(f"\nReading valores_2024_clean.csv...")

    df = pd.read_csv(
        VALORES_FILE,
        usecols=['unit', 'code', 'carrier', 'available_capacity_mw', 'flag_outlier'],
        low_memory=False,
    )
    df_clean = df[df['flag_outlier'] == False]

    # p95 per unit — for direct match
    p95_per_unit = (
        df_clean.groupby('unit')['available_capacity_mw']
        .quantile(P_NOM_PERCENTILE / 100)
    )

    # p95 per plant — for nemo4 match
    p95_per_plant = (
        df_clean.groupby('code')['available_capacity_mw']
        .quantile(P_NOM_PERCENTILE / 100)
    )

    # Apply binational factor
    for nemo4, factor in BINATIONAL_FACTOR.items():
        if nemo4 in p95_per_plant.index:
            p95_per_plant[nemo4] *= factor
            print(f"  {nemo4}: p_nom x {factor} (binational plant)")

    cammesa_units  = set(p95_per_unit.index)
    cammesa_plants = set(p95_per_plant.index)

    # Carrier type per unit and per plant for validation
    type_per_unit  = df_clean.groupby('unit')['carrier'].apply(lambda x: list(x.unique())).to_dict()
    type_per_plant = df_clean.groupby('code')['carrier'].apply(lambda x: list(x.unique())).to_dict()

    print(f"CAMMESA units  : {len(cammesa_units)}")
    print(f"CAMMESA plants : {len(cammesa_plants)}")

    # =========================================================
    # VALIDATE CARRIER VS CAMMESA TYPE
    # =========================================================
    def carrier_compatible(carrier, types):
        valid = CARRIER_VALID_TYPES.get(carrier, [])
        return any(t in types for t in valid)

    exclude_carrier = set()
    for _, row in gen.iterrows():
        carrier    = row['carrier']
        bus_origen = row['bus_name_origen']
        nemo4      = row['nemo4']
        types = type_per_unit.get(bus_origen) or type_per_plant.get(nemo4)
        if types and not carrier_compatible(carrier, types):
            exclude_carrier.add(row['gen_key'])

    if exclude_carrier:
        excl_mw = gen[gen['gen_key'].isin(exclude_carrier)]['pt_mw']
        excl_mw = excl_mw[excl_mw < 9000].sum()
        print(f"\nUnits excluded (incompatible carrier) : {len(exclude_carrier)}")
        for gkey in sorted(exclude_carrier):
            row        = gen[gen['gen_key'] == gkey].iloc[0]
            bus_origen = row['bus_name_origen']
            nemo4      = row['nemo4']
            types      = type_per_unit.get(bus_origen) or type_per_plant.get(nemo4) or []
            print(f"  {gkey:<10} {bus_origen:<12} carrier={row['carrier']:<8} CAMMESA={types}")
        gen = gen[~gen['gen_key'].isin(exclude_carrier)].copy()

    # =========================================================
    # ASSIGN p_nom PER UNIT
    # =========================================================
    p_nom_list       = []
    match_type_list  = []

    pt_sum = gen.groupby('nemo4')['pt_mw'].transform('sum')

    for idx, row in gen.iterrows():
        bus_origen = row['bus_name_origen']
        nemo4      = row['nemo4']
        pt_mw      = row['pt_mw']

        if bus_origen in cammesa_units:
            p_nom = p95_per_unit[bus_origen]
            match_type_list.append('direct')

        elif nemo4 in cammesa_plants:
            pt_total  = pt_sum[idx]
            p_plant   = p95_per_plant[nemo4]
            p_nom     = p_plant * (pt_mw / pt_total) if pt_total > 0 else 0.0
            match_type_list.append('nemo4')

        else:
            p_nom = 0.0
            match_type_list.append('no_match')

        p_nom_list.append(round(max(p_nom, 0.0), 4))

    gen['p_nom']      = p_nom_list
    gen['match_type'] = match_type_list

    # =========================================================
    # SPLIT MATCHED VS UNMATCHED
    # =========================================================
    gen_match    = gen[gen['match_type'] != 'no_match'].copy()
    gen_excluded = gen[gen['match_type'] == 'no_match'].copy()

    print(f"\nDirect match (unit)  : {(gen['match_type']=='direct').sum()}")
    print(f"Match by nemo4       : {(gen['match_type']=='nemo4').sum()}")
    print(f"No match             : {len(gen_excluded)}")

    if len(gen_excluded) > 0:
        excl_summary = gen_excluded.drop_duplicates('nemo4')[
            ['geosadi_name', 'nemo4', 'carrier']
        ].sort_values('nemo4')
        print("\n  Plants with no match in CAMMESA:")
        for _, row in excl_summary.iterrows():
            print(f"    {row['nemo4']:<8} {row['carrier']:<12} {row['geosadi_name']}")

    # =========================================================
    # SUMMARY
    # =========================================================
    print(f"\n{'='*60}")
    print(f"GENERATORS_2024")
    print(f"{'='*60}")
    print(f"\n  Total p_nom : {gen_match['p_nom'].sum():,.1f} MW")
    print(f"\n  By carrier:")
    for carrier, grp in gen_match.groupby('carrier'):
        print(f"    {carrier:<15}: {len(grp):>4} units   p_nom={grp['p_nom'].sum():>10,.1f} MW")

    # =========================================================
    # EXPORT
    # =========================================================
    cols_out = [
        'gen_key', 'bus_name_origen', 'geosadi_name', 'nemo',
        'bus_conexion500kv', 'bus_conexion500kv_name',
        'carrier', 'p_nom', 'lat', 'lon', 'n_jumps', 'path',
    ]
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    gen_match[cols_out].to_csv(OUTPUT_FILE, index=False)

    print(f"\n  Output: {OUTPUT_FILE}  ({len(gen_match)} rows)")
    print("Next: 15_build_loads_2024.py")
    print("=" * 60)


if __name__ == "__main__":
    main()
